page_title: 'Site map'
message:
  value: ''
  format: rich_text
show_front: false
show_titles: false
show_books: {  }
books_expanded: true
show_menus:
  main: main
  account: '0'
  admin: '0'
  footer: '0'
  tools: '0'
show_menus_hidden: false
show_vocabularies:
  news_tags: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 1
rss_taxonomy: -1
css: false
order:
  front: -50
  menus_account: -50
  menus_admin: -50
  menus_footer: -50
  menus_main: -50
  menus_tools: -50
  vocabularies_news_tags: -50
_core:
  default_config_hash: qZeaiLq06xBUfw-JNZtgetxUUMz-J8YCzw_LuhPrk2E
