button_option: stbc_large
comments: 0
late_load: 0
location: content
node_types:
  key_staff_member: key_staff_member
  news: news
  page: page
  landing_page: null
option_extras:
  'Google Plus One:plusone': '0'
  'Facebook Like:fblike': '0'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '"Facebook:facebook","Tweet:twitter","LinkedIn:linkedin","Email:email","ShareThis:sharethis","Pinterest:pinterest"'
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  key_staff_member:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  landing_page:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  news:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
publisherID: dr-bf09cf5d-f027-1e0c-3ff8-5b338de26714
callesi: '0'
